---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    node_name: uhostserver.getuhost.org
    ssl_verify_mode: :verify_peer

platforms:
  - name: ubuntu-14.04
    driver:
      box: ubuntu/trusty64
      customize:
        memory: 2048
  - name: ubuntu-12.04
    driver:
      box: ubuntu/precise64
      customize:
        memory: 1024
  - name: centos-6.5
    driver:
      box: chef/centos-6.5
      customize:
        memory: 1024
  - name: centos-7.0
    driver:
      box: chef/centos-7.0
      customize:
        memory: 1024

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    run_list: ["recipe[uhostchef11server::default]"]
    attributes:
