---
driver:
  name: ec2
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  ssh_key: <%= File.expand_path(ENV['AWS_SSH_KEY']) %>
  security_group_ids: ["sg-68e9c90d"]
  region: <%= ENV['AWS_DEFAULT_REGION'] %>
  availability_zone: <%= ENV['AWS_DEFAULT_REGION'] %>c
  require_chef_omnibus: true
  subnet_id: subnet-2ae12073
  flavor_id: m3.large
  vm_hostname: "local.getuhost.org"

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  client_rb:
    environment: _default
  attributes:
    openssh:
      server:
        password_authentication: 'yes'
        permit_root_login: 'yes'
    cloud:
      public_ipv4: '127.0.0.1'
    authorization:
      sudo:
        users: ['ubuntu']
        passwordless: true

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-67526757
      username: ubuntu
    run_list:
    - recipe[apt]

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[uhostchef11server::default] 
